FROM rust:1.88-bullseye

RUN apt-get update && apt-get install -y \
    gcc-arm-linux-gnueabihf \
    musl-tools

RUN rustup target add armv7-unknown-linux-musleabihf

# Create a symbolic link for the cross-compiler
RUN ln -s /usr/bin/arm-linux-gnueabihf-gcc /usr/bin/arm-linux-musleabihf-gcc